# Generated by Django 4.2 on 2023-04-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('coupon_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yield_to_maturity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_rating', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('issuer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ValuationMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_to_maturity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('modified_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('macaulay_duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convexity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bonddata')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysisMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_to_call', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average_life', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option_adjusted_spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_free_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bonddata')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yield_to_maturity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('credit_spread', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bonddata')),
            ],
        ),
    ]
