# Generated by Django 4.2 on 2023-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bonddata_credit_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonddata',
            name='credit_rating',
            field=models.CharField(default='', max_length=20),
        ),
    ]
