#!c:\users\danie\onedrive\documents\programming\projects\fixed_income_tool\fixed_income_tool\backend\myenv\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
