const sampleBondData = [
    {
        type: 'Government Bond',
        data: {
          issue_date: '2021-04-01',
          maturity_date: '2031-04-01',
          coupon_rate: 0.03,
          years_to_maturity: 10,
          credit_rating: 'AAA',
          currency: 'USD',
          issuer: 'U.S. Treasury',
          bond_cusip: '9128286L8',
          use_api_data: false,
          optional_bond_price: '',
          optional_ytm: '',
          optional_risk_free_yield: '',
          optional_benchmark_yield: '',
          optional_option_value: '',
          option_type: '',
          strike_price: '',
          underlying_price: '',
          risk_free_rate: '',
          volatility: '',
          expiration_date: '',
          face_value: 1000,
          date_first_par_call: '',
        },
      },
      {
        type: 'Corporate Bond',
        data: {
          issue_date: '2021-04-01',
          maturity_date: '2026-04-01',
          coupon_rate: 0.025,
          years_to_maturity: 5,
          credit_rating: 'AA',
          currency: 'USD',
          issuer: 'Microsoft Corporation',
          bond_cusip: '594918AY7',
          use_api_data: false,
          optional_bond_price: '',
          optional_ytm: '',
          optional_risk_free_yield: '',
          optional_benchmark_yield: '',
          optional_option_value: '',
          option_type: '',
          strike_price: '',
          underlying_price: '',
          risk_free_rate: '',
          volatility: '',
          expiration_date: '',
          face_value: 1000,
          date_first_par_call: '2024-04-01',
        },
      },
      {
        type: 'Corporate Bond Callable',
        data: {
          issue_date: '2021-04-01',
          maturity_date: '2031-04-01',
          coupon_rate: 0.04,
          years_to_maturity: 10,
          credit_rating: 'A',
          currency: 'USD',
          issuer: 'Bank of America Corp',
          bond_cusip: '06051GFW4',
          use_api_data: false,
          optional_bond_price: '',
          optional_ytm: '',
          optional_risk_free_yield: '',
          optional_benchmark_yield: '',
          optional_option_value: '',
          option_type: 'Call',
          strike_price: 1050,
          underlying_price: 1040,
          risk_free_rate: 0.02,
          volatility: 0.1,
          expiration_date: '2025-04-01',
          face_value: 1000,
          date_first_par_call: '2025-04-01',
        },
      },
      {
        type: 'Corporate Bond Callable',
        data: {
          issue_date: '2021-04-01',
          maturity_date: '2031-04-01',
          coupon_rate: 0.035,
          years_to_maturity: 10,
          credit_rating: 'AA',
          currency: 'USD',
          issuer: 'Apple Inc.',
          bond_cusip: '037833DD8',
          use_api_data: false,
          optional_bond_price: '',
          optional_ytm: '',
          optional_risk_free_yield: '',
          optional_benchmark_yield: '',
          optional_option_value: '',
          option_type: 'Call',
          strike_price: 1050,
          underlying_price: 1040,
          risk_free_rate: 0.02,
          volatility: 0.1,
          expiration_date: '2025-04-01',
          face_value: 1000,
          date_first_par_call: '2025-04-01',
        },
      },
];

export { sampleBondData };